name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (SonarCloud CLI requires Java)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' 

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: thilak-404
          projectKey: codtech-secure-ci
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run:  |
          sonar-scanner \
           -Dsonar.projectKey=codtech-secure-ci \
           -Dsonar.organization=thilak-404 \
           -Dsonar.sources=. \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=$SONAR_TOKEN
