name: SonarQube Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to latest for better compatibility
      - name: Set up Java (SonarCloud CLI requires Java)
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0  # Updated to latest version
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}